sudo: false

language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

    #
    # Libraries from PlatformIO Library Registry:
    #
    # https://platformio.org/lib/show/1/OneWire
    - platformio lib -g install 872 

script:
- platformio ci --board=esp32thing --lib=. examples/Esp32_NoteOnOffEverySec/Esp32_NoteOnOffEverySec.ino;
- platformio ci --board=huzzah --lib=. examples/Esp8266_2Sessions_NoteOnOffEverySec/Esp8266_2Sessions_NoteOnOffEverySec.ino;
- platformio ci --board=huzzah --lib=. examples/Esp8266_NoteOnOffEverySec/Esp8266_NoteOnOffEverySec.ino;
- platformio ci --board=uno --lib=. examples/EthernetShield_InitiateSession/EthernetShield_InitiateSession.ino;
- platformio ci --board=uno --lib=. examples/EthernetShield_InitiateSessions/EthernetShield_InitiateSessions.ino;
- platformio ci --board=uno --lib=. examples/EthernetShield_NoteOnOffEverySec/EthernetShield_NoteOnOffEverySec.ino;
- platformio ci --board=uno --lib=. examples/EthernetShield_RealTimeMessages/EthernetShield_RealTimeMessages.ino;
- platformio ci --board=uno --lib=. examples/EthernetShield_ReceiveMTC/EthernetShield_ReceiveMTC.ino;
- platformio ci --board=uno --lib=. examples/EthernetShield_SysEx/EthernetShield_SysEx.ino;